'use client';

import { useState } from 'react';
import {
  BookOpen,
  Globe,
  Calculator,
  Microscope,
  History,
  Palette,
  GraduationCap,
  Sparkles,
  Search,
  Puzzle,
} from 'lucide-react';
import { CurriculumLevel } from '../types';

export const useCurriculumByLevel = () => {
  const levels: CurriculumLevel[] = [
    {
      id: 'k-2',
      name: 'Wonder & Foundation',
      grades: 'K-2',
      description: 'Building joy in learning through exploration and discovery',
      color: 'from-yellow-400 to-orange-400',
      bgColor: 'bg-yellow-50',
      borderColor: 'border-yellow-200',
      icon: Sparkles,
      subjects: [
        {
          id: 'language-arts',
          name: 'Language Arts',
          icon: BookOpen,
          pacing: 'Student-Paced',
          topics: ['Phonics & Reading', 'Handwriting', 'Basic Grammar', 'Story Comprehension'],
          description: 'Foundation in reading and writing through systematic phonics',
        },
        {
          id: 'mathematics',
          name: 'Mathematics',
          icon: Calculator,
          pacing: 'Student-Paced',
          topics: ['Number Sense', 'Basic Operations', 'Patterns', 'Problem Solving'],
          description: 'Concrete to abstract mathematical thinking',
        },
        {
          id: 'history-geography',
          name: 'History & Geography',
          icon: Globe,
          pacing: 'School-Paced',
          topics: ['Community Helpers', 'Maps & Globes', 'American Symbols', 'Family History'],
          description: 'Understanding our place in the world',
        },
        {
          id: 'science',
          name: 'Science',
          icon: Microscope,
          pacing: 'School-Paced',
          topics: ['Nature Study', 'Seasons', 'Animals', 'Simple Experiments'],
          description: "Wonder-filled exploration of God's creation",
        },
        {
          id: 'bible',
          name: 'Bible',
          icon: BookOpen,
          pacing: 'School-Paced',
          topics: ['Bible Stories', 'Character Building', 'Memory Verses', 'Prayer'],
          description: 'Foundation of faith through engaging stories',
        },
        {
          id: 'fine-arts',
          name: 'Fine Arts',
          icon: Palette,
          pacing: 'School-Paced',
          topics: ['Art Appreciation', 'Music & Movement', 'Creative Expression'],
          description: 'Developing creativity and appreciation for beauty',
        },
      ],
    },
    {
      id: '3-6',
      name: 'Discovery & Logic',
      grades: '3-6',
      description: 'Developing critical thinking through integrated subjects',
      color: 'from-green-500 to-emerald-500',
      bgColor: 'bg-green-50',
      borderColor: 'border-green-200',
      icon: Search,
      subjects: [
        {
          id: 'language-arts',
          name: 'Language Arts',
          icon: BookOpen,
          pacing: 'Student-Paced',
          topics: ['Grammar & Composition', 'Literature Study', 'Vocabulary', 'Research Skills'],
          description: 'Mastering language through classical texts',
        },
        {
          id: 'mathematics',
          name: 'Mathematics',
          icon: Calculator,
          pacing: 'Student-Paced',
          topics: ['Multiplication/Division', 'Fractions', 'Geometry', 'Word Problems'],
          description: 'Building mathematical reasoning and problem-solving',
        },
        {
          id: 'history',
          name: 'History',
          icon: History,
          pacing: 'School-Paced',
          topics: ['Ancient Civilizations', 'Medieval Times', 'American History', 'World Geography'],
          description: 'Chronological journey through human history',
        },
        {
          id: 'science',
          name: 'Science',
          icon: Microscope,
          pacing: 'School-Paced',
          topics: ['Life Science', 'Earth Science', 'Physical Science', 'Scientific Method'],
          description: 'Systematic exploration of natural phenomena',
        },
        {
          id: 'latin',
          name: 'Latin',
          icon: Globe,
          pacing: 'School-Paced',
          topics: ['Basic Vocabulary', 'Grammar Forms', 'Roman Culture', 'English Derivatives'],
          description: 'Foundation for language mastery and logical thinking',
        },
        {
          id: 'bible-theology',
          name: 'Bible & Theology',
          icon: BookOpen,
          pacing: 'School-Paced',
          topics: ['Old Testament Survey', 'New Testament Survey', 'Christian Worldview', 'Apologetics Basics'],
          description: 'Deeper understanding of Scripture and faith',
        },
      ],
    },
    {
      id: '7-8',
      name: 'Analysis & Reasoning',
      grades: '7-8',
      description: 'Mastering the art of logical thinking and argumentation',
      color: 'from-blue-500 to-indigo-500',
      bgColor: 'bg-blue-50',
      borderColor: 'border-blue-200',
      icon: Puzzle,
      subjects: [
        {
          id: 'logic-rhetoric',
          name: 'Logic & Rhetoric',
          icon: BookOpen,
          pacing: 'School-Paced',
          topics: ['Formal Logic', 'Argumentation', 'Critical Analysis', 'Debate Skills'],
          description: 'Learning to think clearly and argue persuasively',
        },
        {
          id: 'advanced-mathematics',
          name: 'Advanced Mathematics',
          icon: Calculator,
          pacing: 'Student-Paced',
          topics: ['Pre-Algebra', 'Algebra I', 'Geometry Foundations', 'Mathematical Proofs'],
          description: 'Abstract mathematical thinking and problem-solving',
        },
        {
          id: 'literature-composition',
          name: 'Literature & Composition',
          icon: BookOpen,
          pacing: 'Student-Paced',
          topics: ['Classic Literature', 'Essay Writing', 'Literary Analysis', 'Research Papers'],
          description: 'Deep engagement with great texts and ideas',
        },
        {
          id: 'integrated-science',
          name: 'Integrated Science',
          icon: Microscope,
          pacing: 'School-Paced',
          topics: ['Physical Science', 'Biology', 'Chemistry Basics', 'Lab Skills'],
          description: 'Rigorous scientific investigation and experimentation',
        },
        {
          id: 'history-government',
          name: 'History & Government',
          icon: History,
          pacing: 'School-Paced',
          topics: ['U.S. History', 'Government & Civics', 'World History', 'Current Events'],
          description: 'Understanding our heritage and civic responsibilities',
        },
        {
          id: 'theology-worldview',
          name: 'Theology & Worldview',
          icon: BookOpen,
          pacing: 'School-Paced',
          topics: ['Systematic Theology', 'Worldview Analysis', 'Apologetics', 'Ethics'],
          description: 'Developing a coherent biblical worldview',
        },
      ],
    },
    {
      id: '9-12',
      name: 'Mastery & Rhetoric',
      grades: '9-12',
      description: 'Preparing for college and life with advanced scholarship',
      color: 'from-purple-500 to-pink-500',
      bgColor: 'bg-purple-50',
      borderColor: 'border-purple-200',
      icon: GraduationCap,
      subjects: [
        {
          id: 'rhetoric-communication',
          name: 'Rhetoric & Communication',
          icon: BookOpen,
          pacing: 'School-Paced',
          topics: ['Classical Rhetoric', 'Public Speaking', 'Persuasive Writing', 'Senior Thesis'],
          description: 'Mastering the art of persuasion and communication',
        },
        {
          id: 'advanced-math',
          name: 'Advanced Mathematics',
          icon: Calculator,
          pacing: 'Student-Paced',
          topics: ['Algebra II', 'Pre-Calculus', 'Calculus', 'Statistics'],
          description: 'College-level mathematical preparation',
        },
        {
          id: 'great-books',
          name: 'Great Books',
          icon: BookOpen,
          pacing: 'School-Paced',
          topics: ['Western Classics', 'Philosophy', 'Literary Criticism', 'Creative Writing'],
          description: 'Engaging with the greatest minds in history',
        },
        {
          id: 'advanced-sciences',
          name: 'Advanced Sciences',
          icon: Microscope,
          pacing: 'School-Paced',
          topics: ['Biology', 'Chemistry', 'Physics', 'AP Sciences'],
          description: 'College-preparatory laboratory sciences',
        },
        {
          id: 'history-philosophy',
          name: 'History & Philosophy',
          icon: History,
          pacing: 'School-Paced',
          topics: ['Ancient Philosophy', 'Modern History', 'Economics', 'Political Philosophy'],
          description: 'Understanding ideas that shaped our world',
        },
        {
          id: 'advanced-theology',
          name: 'Advanced Theology',
          icon: BookOpen,
          pacing: 'School-Paced',
          topics: ['Biblical Languages', 'Church History', 'Contemporary Issues', 'Missions'],
          description: 'Deep theological study and practical application',
        },
      ],
    },
  ];

  const [activeLevelId, setActiveLevelId] = useState(levels[0].id);
  const selectedLevel = levels.find((level) => level.id === activeLevelId)!;
  const subjects = selectedLevel.subjects;
  const handleLevelSelect = (id: string) => setActiveLevelId(id);

  return { levels, selectedLevel, subjects, handleLevelSelect };
};
